"""JLPT N5 kanji seed data — 80 characters with readings, meanings, and vocab links."""

import logging

from app.database.connection import get_db

logger = logging.getLogger("life-master.kanji-seed")

# Fields: character, meaning_ko, meaning_en, onyomi, kunyomi, jlpt_level, grade,
#         stroke_count, radicals, order_index

N5_KANJI = [
    # ── Numbers ───────────────────────────────────────────────────────────────
    {
        "character": "一",
        "meaning_ko": "하나, 일",
        "meaning_en": "one",
        "onyomi": "イチ,イツ",
        "kunyomi": "ひと.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 1,
        "radicals": "一",
        "order_index": 1,
    },
    {
        "character": "二",
        "meaning_ko": "둘, 이",
        "meaning_en": "two",
        "onyomi": "ニ,ジ",
        "kunyomi": "ふた.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "二",
        "order_index": 2,
    },
    {
        "character": "三",
        "meaning_ko": "셋, 삼",
        "meaning_en": "three",
        "onyomi": "サン",
        "kunyomi": "み.つ,みっ.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "一",
        "order_index": 3,
    },
    {
        "character": "四",
        "meaning_ko": "넷, 사",
        "meaning_en": "four",
        "onyomi": "シ",
        "kunyomi": "よ.つ,よっ.つ,よん",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "囗",
        "order_index": 4,
    },
    {
        "character": "五",
        "meaning_ko": "다섯, 오",
        "meaning_en": "five",
        "onyomi": "ゴ",
        "kunyomi": "いつ.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "二",
        "order_index": 5,
    },
    {
        "character": "六",
        "meaning_ko": "여섯, 육",
        "meaning_en": "six",
        "onyomi": "ロク",
        "kunyomi": "むっ.つ,む.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "亠",
        "order_index": 6,
    },
    {
        "character": "七",
        "meaning_ko": "일곱, 칠",
        "meaning_en": "seven",
        "onyomi": "シチ",
        "kunyomi": "なな.つ,なな",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "一",
        "order_index": 7,
    },
    {
        "character": "八",
        "meaning_ko": "여덟, 팔",
        "meaning_en": "eight",
        "onyomi": "ハチ",
        "kunyomi": "やっ.つ,や.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "八",
        "order_index": 8,
    },
    {
        "character": "九",
        "meaning_ko": "아홉, 구",
        "meaning_en": "nine",
        "onyomi": "キュウ,ク",
        "kunyomi": "ここの.つ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "乙",
        "order_index": 9,
    },
    {
        "character": "十",
        "meaning_ko": "열, 십",
        "meaning_en": "ten",
        "onyomi": "ジュウ,ジッ",
        "kunyomi": "とお,と",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "十",
        "order_index": 10,
    },
    {
        "character": "百",
        "meaning_ko": "백",
        "meaning_en": "hundred",
        "onyomi": "ヒャク",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "一",
        "order_index": 11,
    },
    {
        "character": "千",
        "meaning_ko": "천",
        "meaning_en": "thousand",
        "onyomi": "セン",
        "kunyomi": "ち",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "十",
        "order_index": 12,
    },
    {
        "character": "万",
        "meaning_ko": "만",
        "meaning_en": "ten thousand",
        "onyomi": "マン,バン",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 3,
        "radicals": "一",
        "order_index": 13,
    },
    {
        "character": "円",
        "meaning_ko": "엔, 원, 동그라미",
        "meaning_en": "yen, circle",
        "onyomi": "エン",
        "kunyomi": "まる.い",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "囗",
        "order_index": 14,
    },
    # ── Time ──────────────────────────────────────────────────────────────────
    {
        "character": "日",
        "meaning_ko": "날, 해, 일본",
        "meaning_en": "day, sun, Japan",
        "onyomi": "ニチ,ジツ",
        "kunyomi": "ひ,か",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "日",
        "order_index": 15,
    },
    {
        "character": "月",
        "meaning_ko": "달, 월",
        "meaning_en": "moon, month",
        "onyomi": "ゲツ,ガツ",
        "kunyomi": "つき",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "月",
        "order_index": 16,
    },
    {
        "character": "火",
        "meaning_ko": "불, 화요일",
        "meaning_en": "fire, Tuesday",
        "onyomi": "カ",
        "kunyomi": "ひ,ほ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "火",
        "order_index": 17,
    },
    {
        "character": "水",
        "meaning_ko": "물, 수요일",
        "meaning_en": "water, Wednesday",
        "onyomi": "スイ",
        "kunyomi": "みず",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "水",
        "order_index": 18,
    },
    {
        "character": "木",
        "meaning_ko": "나무, 목요일",
        "meaning_en": "tree, wood, Thursday",
        "onyomi": "モク,ボク",
        "kunyomi": "き,こ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "木",
        "order_index": 19,
    },
    {
        "character": "金",
        "meaning_ko": "금, 쇠, 돈, 금요일",
        "meaning_en": "gold, money, Friday",
        "onyomi": "キン,コン",
        "kunyomi": "かね,かな",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 8,
        "radicals": "金",
        "order_index": 20,
    },
    {
        "character": "土",
        "meaning_ko": "흙, 토요일",
        "meaning_en": "earth, soil, Saturday",
        "onyomi": "ド,ト",
        "kunyomi": "つち",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "土",
        "order_index": 21,
    },
    {
        "character": "年",
        "meaning_ko": "해, 년",
        "meaning_en": "year",
        "onyomi": "ネン",
        "kunyomi": "とし",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "干",
        "order_index": 22,
    },
    {
        "character": "時",
        "meaning_ko": "때, 시각",
        "meaning_en": "time, hour",
        "onyomi": "ジ",
        "kunyomi": "とき",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 10,
        "radicals": "日",
        "order_index": 23,
    },
    {
        "character": "間",
        "meaning_ko": "사이, 시간",
        "meaning_en": "interval, space, time",
        "onyomi": "カン,ケン",
        "kunyomi": "あいだ,ま",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 12,
        "radicals": "門",
        "order_index": 24,
    },
    {
        "character": "分",
        "meaning_ko": "분, 나누다",
        "meaning_en": "minute, part, understand",
        "onyomi": "フン,ブン,ブ",
        "kunyomi": "わ.かる,わ.ける",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 4,
        "radicals": "刀",
        "order_index": 25,
    },
    {
        "character": "半",
        "meaning_ko": "반, 절반",
        "meaning_en": "half",
        "onyomi": "ハン",
        "kunyomi": "なか.ば",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 5,
        "radicals": "十",
        "order_index": 26,
    },
    {
        "character": "前",
        "meaning_ko": "앞, 전",
        "meaning_en": "before, front",
        "onyomi": "ゼン",
        "kunyomi": "まえ",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 9,
        "radicals": "刀",
        "order_index": 27,
    },
    {
        "character": "後",
        "meaning_ko": "뒤, 후",
        "meaning_en": "after, behind",
        "onyomi": "ゴ,コウ",
        "kunyomi": "あと,うし.ろ,のち",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 9,
        "radicals": "彳",
        "order_index": 28,
    },
    {
        "character": "午",
        "meaning_ko": "낮 12시, 오",
        "meaning_en": "noon",
        "onyomi": "ゴ",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 4,
        "radicals": "十",
        "order_index": 29,
    },
    # ── Directions & Position ─────────────────────────────────────────────────
    {
        "character": "上",
        "meaning_ko": "위, 상",
        "meaning_en": "above, up",
        "onyomi": "ジョウ,ショウ",
        "kunyomi": "うえ,うわ,かみ,あ.げる,のぼ.る",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "一",
        "order_index": 30,
    },
    {
        "character": "下",
        "meaning_ko": "아래, 하",
        "meaning_en": "below, down",
        "onyomi": "カ,ゲ",
        "kunyomi": "した,しも,お.りる,さ.げる",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "一",
        "order_index": 31,
    },
    {
        "character": "中",
        "meaning_ko": "가운데, 중",
        "meaning_en": "middle, inside",
        "onyomi": "チュウ",
        "kunyomi": "なか",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "口",
        "order_index": 32,
    },
    {
        "character": "大",
        "meaning_ko": "크다, 대",
        "meaning_en": "big, large",
        "onyomi": "ダイ,タイ",
        "kunyomi": "おお.きい,おお",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "大",
        "order_index": 33,
    },
    {
        "character": "小",
        "meaning_ko": "작다, 소",
        "meaning_en": "small, little",
        "onyomi": "ショウ",
        "kunyomi": "ちい.さい,こ,お",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "小",
        "order_index": 34,
    },
    {
        "character": "右",
        "meaning_ko": "오른쪽, 우",
        "meaning_en": "right",
        "onyomi": "ウ,ユウ",
        "kunyomi": "みぎ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "口",
        "order_index": 35,
    },
    {
        "character": "左",
        "meaning_ko": "왼쪽, 좌",
        "meaning_en": "left",
        "onyomi": "サ",
        "kunyomi": "ひだり",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "工",
        "order_index": 36,
    },
    {
        "character": "北",
        "meaning_ko": "북쪽, 북",
        "meaning_en": "north",
        "onyomi": "ホク",
        "kunyomi": "きた",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 5,
        "radicals": "匕",
        "order_index": 37,
    },
    {
        "character": "南",
        "meaning_ko": "남쪽, 남",
        "meaning_en": "south",
        "onyomi": "ナン,ナ",
        "kunyomi": "みなみ",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 9,
        "radicals": "十",
        "order_index": 38,
    },
    {
        "character": "東",
        "meaning_ko": "동쪽, 동",
        "meaning_en": "east",
        "onyomi": "トウ",
        "kunyomi": "ひがし",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 8,
        "radicals": "木",
        "order_index": 39,
    },
    {
        "character": "西",
        "meaning_ko": "서쪽, 서",
        "meaning_en": "west",
        "onyomi": "セイ,サイ",
        "kunyomi": "にし",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 6,
        "radicals": "西",
        "order_index": 40,
    },
    {
        "character": "外",
        "meaning_ko": "바깥, 외",
        "meaning_en": "outside, foreign",
        "onyomi": "ガイ,ゲ",
        "kunyomi": "そと,ほか,はず.れる",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 5,
        "radicals": "夕",
        "order_index": 41,
    },
    # ── People & Family ───────────────────────────────────────────────────────
    {
        "character": "人",
        "meaning_ko": "사람, 인",
        "meaning_en": "person, people",
        "onyomi": "ジン,ニン",
        "kunyomi": "ひと",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "人",
        "order_index": 42,
    },
    {
        "character": "男",
        "meaning_ko": "남자, 남",
        "meaning_en": "man, male",
        "onyomi": "ダン,ナン",
        "kunyomi": "おとこ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 7,
        "radicals": "田",
        "order_index": 43,
    },
    {
        "character": "女",
        "meaning_ko": "여자, 여",
        "meaning_en": "woman, female",
        "onyomi": "ジョ,ニョ,ニョウ",
        "kunyomi": "おんな,め",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "女",
        "order_index": 44,
    },
    {
        "character": "子",
        "meaning_ko": "아이, 자",
        "meaning_en": "child",
        "onyomi": "シ,ス",
        "kunyomi": "こ,ね",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "子",
        "order_index": 45,
    },
    {
        "character": "父",
        "meaning_ko": "아버지, 부",
        "meaning_en": "father",
        "onyomi": "フ",
        "kunyomi": "ちち",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 4,
        "radicals": "父",
        "order_index": 46,
    },
    {
        "character": "母",
        "meaning_ko": "어머니, 모",
        "meaning_en": "mother",
        "onyomi": "ボ",
        "kunyomi": "はは",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 5,
        "radicals": "母",
        "order_index": 47,
    },
    {
        "character": "友",
        "meaning_ko": "친구, 우",
        "meaning_en": "friend",
        "onyomi": "ユウ",
        "kunyomi": "とも",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 4,
        "radicals": "又",
        "order_index": 48,
    },
    {
        "character": "先",
        "meaning_ko": "먼저, 선",
        "meaning_en": "before, ahead, previous",
        "onyomi": "セン",
        "kunyomi": "さき",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "儿",
        "order_index": 49,
    },
    {
        "character": "生",
        "meaning_ko": "살다, 생",
        "meaning_en": "life, live, birth",
        "onyomi": "セイ,ショウ",
        "kunyomi": "い.きる,う.まれる,なま,は.える",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "生",
        "order_index": 50,
    },
    # ── School & Learning ─────────────────────────────────────────────────────
    {
        "character": "学",
        "meaning_ko": "배우다, 학",
        "meaning_en": "study, learning",
        "onyomi": "ガク",
        "kunyomi": "まな.ぶ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 8,
        "radicals": "子",
        "order_index": 51,
    },
    {
        "character": "校",
        "meaning_ko": "학교, 교",
        "meaning_en": "school",
        "onyomi": "コウ",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 10,
        "radicals": "木",
        "order_index": 52,
    },
    # ── Objects & Things ──────────────────────────────────────────────────────
    {
        "character": "本",
        "meaning_ko": "책, 본래",
        "meaning_en": "book, origin",
        "onyomi": "ホン",
        "kunyomi": "もと",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "木",
        "order_index": 53,
    },
    {
        "character": "書",
        "meaning_ko": "쓰다, 서",
        "meaning_en": "write, book",
        "onyomi": "ショ",
        "kunyomi": "か.く",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 10,
        "radicals": "曰",
        "order_index": 54,
    },
    {
        "character": "車",
        "meaning_ko": "차, 거",
        "meaning_en": "car, vehicle",
        "onyomi": "シャ",
        "kunyomi": "くるま",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 7,
        "radicals": "車",
        "order_index": 55,
    },
    {
        "character": "電",
        "meaning_ko": "전기, 전",
        "meaning_en": "electricity",
        "onyomi": "デン",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 13,
        "radicals": "雨",
        "order_index": 56,
    },
    {
        "character": "話",
        "meaning_ko": "이야기, 화",
        "meaning_en": "talk, story",
        "onyomi": "ワ",
        "kunyomi": "はな.す,はなし",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 13,
        "radicals": "言",
        "order_index": 57,
    },
    {
        "character": "語",
        "meaning_ko": "말, 어",
        "meaning_en": "language, word",
        "onyomi": "ゴ",
        "kunyomi": "かた.る,かた.らう",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 14,
        "radicals": "言",
        "order_index": 58,
    },
    {
        "character": "国",
        "meaning_ko": "나라, 국",
        "meaning_en": "country, nation",
        "onyomi": "コク",
        "kunyomi": "くに",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 8,
        "radicals": "囗",
        "order_index": 59,
    },
    {
        "character": "会",
        "meaning_ko": "만나다, 회",
        "meaning_en": "meet, association",
        "onyomi": "カイ,エ",
        "kunyomi": "あ.う",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 6,
        "radicals": "人",
        "order_index": 60,
    },
    {
        "character": "社",
        "meaning_ko": "회사, 신사",
        "meaning_en": "company, shrine",
        "onyomi": "シャ",
        "kunyomi": "やしろ",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 7,
        "radicals": "示",
        "order_index": 61,
    },
    # ── Nature ────────────────────────────────────────────────────────────────
    {
        "character": "天",
        "meaning_ko": "하늘, 천",
        "meaning_en": "heaven, sky",
        "onyomi": "テン",
        "kunyomi": "あめ,あま",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "大",
        "order_index": 62,
    },
    {
        "character": "気",
        "meaning_ko": "기운, 기",
        "meaning_en": "spirit, energy, mood",
        "onyomi": "キ,ケ",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "气",
        "order_index": 63,
    },
    {
        "character": "雨",
        "meaning_ko": "비, 우",
        "meaning_en": "rain",
        "onyomi": "ウ",
        "kunyomi": "あめ,あま",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 8,
        "radicals": "雨",
        "order_index": 64,
    },
    {
        "character": "山",
        "meaning_ko": "산",
        "meaning_en": "mountain",
        "onyomi": "サン",
        "kunyomi": "やま",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "山",
        "order_index": 65,
    },
    {
        "character": "川",
        "meaning_ko": "강, 천",
        "meaning_en": "river",
        "onyomi": "セン",
        "kunyomi": "かわ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "川",
        "order_index": 66,
    },
    {
        "character": "花",
        "meaning_ko": "꽃, 화",
        "meaning_en": "flower",
        "onyomi": "カ",
        "kunyomi": "はな",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 7,
        "radicals": "艸",
        "order_index": 67,
    },
    # ── Actions (Verbs) ───────────────────────────────────────────────────────
    {
        "character": "食",
        "meaning_ko": "먹다, 식",
        "meaning_en": "eat, food",
        "onyomi": "ショク,ジキ",
        "kunyomi": "た.べる,く.う",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 9,
        "radicals": "食",
        "order_index": 68,
    },
    {
        "character": "飲",
        "meaning_ko": "마시다, 음",
        "meaning_en": "drink",
        "onyomi": "イン",
        "kunyomi": "の.む",
        "jlpt_level": "N5",
        "grade": 3,
        "stroke_count": 12,
        "radicals": "食",
        "order_index": 69,
    },
    {
        "character": "休",
        "meaning_ko": "쉬다, 휴",
        "meaning_en": "rest",
        "onyomi": "キュウ",
        "kunyomi": "やす.む,やす.み",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "人",
        "order_index": 70,
    },
    {
        "character": "見",
        "meaning_ko": "보다, 견",
        "meaning_en": "see, look",
        "onyomi": "ケン",
        "kunyomi": "み.る,み.える,み.せる",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 7,
        "radicals": "見",
        "order_index": 71,
    },
    {
        "character": "聞",
        "meaning_ko": "듣다, 문",
        "meaning_en": "hear, ask, listen",
        "onyomi": "ブン,モン",
        "kunyomi": "き.く,き.こえる",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 14,
        "radicals": "耳",
        "order_index": 72,
    },
    {
        "character": "読",
        "meaning_ko": "읽다, 독",
        "meaning_en": "read",
        "onyomi": "ドク,トク,トウ",
        "kunyomi": "よ.む",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 14,
        "radicals": "言",
        "order_index": 73,
    },
    {
        "character": "買",
        "meaning_ko": "사다, 매",
        "meaning_en": "buy",
        "onyomi": "バイ",
        "kunyomi": "か.う",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 12,
        "radicals": "貝",
        "order_index": 74,
    },
    {
        "character": "入",
        "meaning_ko": "들어가다, 입",
        "meaning_en": "enter, insert",
        "onyomi": "ニュウ,ジュ",
        "kunyomi": "い.る,い.れる,はい.る",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 2,
        "radicals": "入",
        "order_index": 75,
    },
    {
        "character": "出",
        "meaning_ko": "나오다, 출",
        "meaning_en": "exit, come out",
        "onyomi": "シュツ,スイ",
        "kunyomi": "で.る,だ.す",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "凵",
        "order_index": 76,
    },
    {
        "character": "立",
        "meaning_ko": "서다, 립",
        "meaning_en": "stand",
        "onyomi": "リツ,リュウ",
        "kunyomi": "た.つ,た.てる",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "立",
        "order_index": 77,
    },
    # ── Descriptors ───────────────────────────────────────────────────────────
    {
        "character": "名",
        "meaning_ko": "이름, 명",
        "meaning_en": "name, famous",
        "onyomi": "メイ,ミョウ",
        "kunyomi": "な",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "夕",
        "order_index": 78,
    },
    {
        "character": "何",
        "meaning_ko": "무엇, 하",
        "meaning_en": "what, how many",
        "onyomi": "カ",
        "kunyomi": "なに,なん",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 7,
        "radicals": "人",
        "order_index": 79,
    },
    {
        "character": "毎",
        "meaning_ko": "매번, 매",
        "meaning_en": "every",
        "onyomi": "マイ",
        "kunyomi": "",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 6,
        "radicals": "母",
        "order_index": 80,
    },
    {
        "character": "新",
        "meaning_ko": "새롭다, 신",
        "meaning_en": "new",
        "onyomi": "シン",
        "kunyomi": "あたら.しい,あら,にい",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 13,
        "radicals": "斤",
        "order_index": 81,
    },
    {
        "character": "古",
        "meaning_ko": "오래되다, 고",
        "meaning_en": "old",
        "onyomi": "コ",
        "kunyomi": "ふる.い,ふる",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 5,
        "radicals": "十",
        "order_index": 82,
    },
    {
        "character": "長",
        "meaning_ko": "길다, 장",
        "meaning_en": "long, leader",
        "onyomi": "チョウ",
        "kunyomi": "なが.い,おさ",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 8,
        "radicals": "長",
        "order_index": 83,
    },
    {
        "character": "高",
        "meaning_ko": "높다, 비싸다, 고",
        "meaning_en": "high, expensive",
        "onyomi": "コウ",
        "kunyomi": "たか.い,たか,たか.まる",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 10,
        "radicals": "高",
        "order_index": 84,
    },
    {
        "character": "安",
        "meaning_ko": "싸다, 안전하다, 안",
        "meaning_en": "cheap, safe, peaceful",
        "onyomi": "アン",
        "kunyomi": "やす.い,やす",
        "jlpt_level": "N5",
        "grade": 3,
        "stroke_count": 6,
        "radicals": "女",
        "order_index": 85,
    },
    {
        "character": "白",
        "meaning_ko": "희다, 백",
        "meaning_en": "white",
        "onyomi": "ハク,ビャク",
        "kunyomi": "しろ,しら,しろ.い",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "白",
        "order_index": 86,
    },
    # ── Body Parts ────────────────────────────────────────────────────────────
    {
        "character": "口",
        "meaning_ko": "입, 구",
        "meaning_en": "mouth",
        "onyomi": "コウ,ク",
        "kunyomi": "くち",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 3,
        "radicals": "口",
        "order_index": 87,
    },
    {
        "character": "目",
        "meaning_ko": "눈, 목",
        "meaning_en": "eye",
        "onyomi": "モク,ボク",
        "kunyomi": "め,ま",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 5,
        "radicals": "目",
        "order_index": 88,
    },
    {
        "character": "耳",
        "meaning_ko": "귀, 이",
        "meaning_en": "ear",
        "onyomi": "ジ",
        "kunyomi": "みみ",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 6,
        "radicals": "耳",
        "order_index": 89,
    },
    {
        "character": "手",
        "meaning_ko": "손, 수",
        "meaning_en": "hand",
        "onyomi": "シュ,ズ",
        "kunyomi": "て,た",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 4,
        "radicals": "手",
        "order_index": 90,
    },
    {
        "character": "足",
        "meaning_ko": "발, 족",
        "meaning_en": "foot, leg, enough",
        "onyomi": "ソク",
        "kunyomi": "あし,た.りる,た.す",
        "jlpt_level": "N5",
        "grade": 1,
        "stroke_count": 7,
        "radicals": "足",
        "order_index": 91,
    },
    # ── Movement ──────────────────────────────────────────────────────────────
    {
        "character": "行",
        "meaning_ko": "가다, 행",
        "meaning_en": "go, conduct",
        "onyomi": "コウ,ギョウ,アン",
        "kunyomi": "い.く,ゆ.く,おこな.う",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 6,
        "radicals": "彳",
        "order_index": 92,
    },
    {
        "character": "来",
        "meaning_ko": "오다, 래",
        "meaning_en": "come",
        "onyomi": "ライ",
        "kunyomi": "く.る,き.たる",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 7,
        "radicals": "木",
        "order_index": 93,
    },
    {
        "character": "帰",
        "meaning_ko": "돌아가다, 귀",
        "meaning_en": "return home",
        "onyomi": "キ",
        "kunyomi": "かえ.る,かえ.す",
        "jlpt_level": "N5",
        "grade": 2,
        "stroke_count": 10,
        "radicals": "刀",
        "order_index": 94,
    },
]


async def seed_kanji_data() -> int:
    """Seed N5 kanji into jp_kanji table and link to existing vocabulary."""
    db = await get_db()
    count = 0

    for kanji in N5_KANJI:
        # Check for duplicate by character
        cursor = await db.execute(
            "SELECT id FROM jp_kanji WHERE character = ?",
            (kanji["character"],),
        )
        existing = await cursor.fetchone()
        if existing:
            kanji_id = existing[0]
        else:
            await db.execute(
                """INSERT INTO jp_kanji
                   (character, meaning_ko, meaning_en, onyomi, kunyomi,
                    jlpt_level, grade, stroke_count, radicals, order_index)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    kanji["character"],
                    kanji["meaning_ko"],
                    kanji["meaning_en"],
                    kanji["onyomi"],
                    kanji["kunyomi"],
                    kanji["jlpt_level"],
                    kanji["grade"],
                    kanji["stroke_count"],
                    kanji["radicals"],
                    kanji["order_index"],
                ),
            )
            cursor = await db.execute("SELECT last_insert_rowid()")
            kanji_id = (await cursor.fetchone())[0]
            count += 1

        # Link to vocabulary: find all vocab words containing this kanji character
        cursor = await db.execute(
            "SELECT id FROM jp_vocabulary WHERE word LIKE ?",
            (f"%{kanji['character']}%",),
        )
        vocab_rows = await cursor.fetchall()
        for row in vocab_rows:
            vocab_id = row[0]
            try:
                await db.execute(
                    """INSERT OR IGNORE INTO jp_kanji_vocab_link (kanji_id, vocab_id)
                       VALUES (?, ?)""",
                    (kanji_id, vocab_id),
                )
            except Exception as e:
                logger.warning(
                    "Failed to link kanji %s to vocab_id %d: %s",
                    kanji["character"],
                    vocab_id,
                    e,
                )

    await db.commit()
    logger.info("Seeded %d new N5 kanji entries", count)
    return count
