"""JLPT vocabulary seed data + J-POP/anime/game source content."""

import json
import logging

from app.database.connection import get_db

logger = logging.getLogger("life-master.jp-seed")

# ── JLPT N5 Core Vocabulary (샘플 50개 — API로 추가 가능) ──

SEED_VOCAB = [
    # N5 — 기초
    ("食べる", "たべる", "먹다", "N5", "verb", "毎日ご飯を食べる。", "매일 밥을 먹는다."),
    ("飲む", "のむ", "마시다", "N5", "verb", "水を飲む。", "물을 마신다."),
    ("行く", "いく", "가다", "N5", "verb", "学校に行く。", "학교에 간다."),
    ("来る", "くる", "오다", "N5", "verb", "友達が来る。", "친구가 온다."),
    ("見る", "みる", "보다", "N5", "verb", "映画を見る。", "영화를 본다."),
    ("聞く", "きく", "듣다", "N5", "verb", "音楽を聞く。", "음악을 듣는다."),
    ("読む", "よむ", "읽다", "N5", "verb", "本を読む。", "책을 읽는다."),
    ("書く", "かく", "쓰다", "N5", "verb", "手紙を書く。", "편지를 쓴다."),
    ("話す", "はなす", "말하다", "N5", "verb", "日本語を話す。", "일본어를 말한다."),
    ("買う", "かう", "사다", "N5", "verb", "本を買う。", "책을 산다."),
    ("大きい", "おおきい", "크다", "N5", "adjective", "大きい家。", "큰 집."),
    ("小さい", "ちいさい", "작다", "N5", "adjective", "小さい猫。", "작은 고양이."),
    ("新しい", "あたらしい", "새롭다", "N5", "adjective", "新しい靴を買った。", "새 신발을 샀다."),
    ("古い", "ふるい", "오래되다", "N5", "adjective", "古い建物。", "오래된 건물."),
    ("高い", "たかい", "높다/비싸다", "N5", "adjective", "高い山。", "높은 산."),
    ("安い", "やすい", "싸다", "N5", "adjective", "安いレストラン。", "저렴한 레스토랑."),
    ("人", "ひと", "사람", "N5", "noun", "あの人は先生です。", "저 사람은 선생님입니다."),
    ("時間", "じかん", "시간", "N5", "noun", "時間がない。", "시간이 없다."),
    ("今日", "きょう", "오늘", "N5", "noun", "今日は暑い。", "오늘은 덥다."),
    ("明日", "あした", "내일", "N5", "noun", "明日学校に行く。", "내일 학교에 간다."),
    # N4
    ("届ける", "とどける", "전달하다", "N4", "verb", "荷物を届ける。", "짐을 전달한다."),
    ("決める", "きめる", "정하다", "N4", "verb", "予定を決める。", "예정을 정한다."),
    ("集める", "あつめる", "모으다", "N4", "verb", "切手を集める。", "우표를 모은다."),
    ("経験", "けいけん", "경험", "N4", "noun", "いい経験になった。", "좋은 경험이 됐다."),
    ("習慣", "しゅうかん", "습관", "N4", "noun", "良い習慣を作る。", "좋은 습관을 만든다."),
    ("特別", "とくべつ", "특별", "N4", "na-adjective", "特別な日。", "특별한 날."),
    ("簡単", "かんたん", "간단", "N4", "na-adjective", "簡単な問題。", "간단한 문제."),
    ("複雑", "ふくざつ", "복잡", "N4", "na-adjective", "複雑な気持ち。", "복잡한 기분."),
    # N3
    ("影響", "えいきょう", "영향", "N3", "noun", "環境に影響を与える。", "환경에 영향을 준다."),
    ("努力", "どりょく", "노력", "N3", "noun", "努力が必要だ。", "노력이 필요하다."),
    ("挑戦", "ちょうせん", "도전", "N3", "noun", "新しいことに挑戦する。", "새로운 것에 도전한다."),
    ("成長", "せいちょう", "성장", "N3", "noun", "子供の成長。", "아이의 성장."),
    ("関係", "かんけい", "관계", "N3", "noun", "人間関係。", "인간관계."),
    ("比較", "ひかく", "비교", "N3", "noun", "二つを比較する。", "둘을 비교한다."),
    ("判断", "はんだん", "판단", "N3", "noun", "正しい判断。", "올바른 판단."),
    ("確認", "かくにん", "확인", "N3", "noun", "予約を確認する。", "예약을 확인한다."),
    # N2
    ("貢献", "こうけん", "공헌", "N2", "noun", "社会に貢献する。", "사회에 공헌한다."),
    ("維持", "いじ", "유지", "N2", "noun", "健康を維持する。", "건강을 유지한다."),
    ("対応", "たいおう", "대응", "N2", "noun", "問題に対応する。", "문제에 대응한다."),
    ("効率", "こうりつ", "효율", "N2", "noun", "効率を上げる。", "효율을 올린다."),
    ("環境", "かんきょう", "환경", "N2", "noun", "自然環境を守る。", "자연환경을 지킨다."),
    ("展開", "てんかい", "전개", "N2", "noun", "物語が展開する。", "이야기가 전개된다."),
    # N1
    ("概念", "がいねん", "개념", "N1", "noun", "基本的な概念。", "기본적인 개념."),
    ("把握", "はあく", "파악", "N1", "noun", "状況を把握する。", "상황을 파악한다."),
    ("妥協", "だきょう", "타협", "N1", "noun", "妥協しない。", "타협하지 않는다."),
    ("矛盾", "むじゅん", "모순", "N1", "noun", "矛盾した意見。", "모순된 의견."),
    ("洞察", "どうさつ", "통찰", "N1", "noun", "深い洞察力。", "깊은 통찰력."),
    ("齟齬", "そご", "어긋남", "N1", "noun", "意見に齟齬が生じる。", "의견에 어긋남이 생긴다."),
]

# ── J-POP / Anime / Game Sources ──

SEED_SOURCES = [
    # ═══════════════════════════════════════════════════════════
    # J-POP / Anime Songs  (25곡)
    # ═══════════════════════════════════════════════════════════
    {
        "title": "Lemon",
        "artist": "米津玄師",
        "source_type": "song",
        "content_ja": "夢ならばどれほどよかったでしょう\n未だにあなたのことを夢にみる\n忘れた物を取りに帰るように\n古びた思い出の埃を払う",
        "content_ko": "꿈이라면 얼마나 좋았을까\n아직도 당신을 꿈에서 봐\n잊어버린 것을 가지러 돌아가듯\n빛바랜 추억의 먼지를 털어낸다",
        "difficulty": "N3",
        "tags": '["jpop", "ballad"]',
    },
    {
        "title": "打上花火",
        "artist": "DAOKO × 米津玄師",
        "source_type": "song",
        "content_ja": "あの日見渡した渚を\n今も思い出すんだ\n砂の上に刻んだ言葉\n君の後ろ姿",
        "content_ko": "그날 바라봤던 해변을\n지금도 떠올린다\n모래 위에 새긴 말\n너의 뒷모습",
        "difficulty": "N4",
        "tags": '["jpop", "anime-song"]',
    },
    {
        "title": "夜に駆ける",
        "artist": "YOASOBI",
        "source_type": "song",
        "content_ja": "沈むように溶けてゆくように\n二人だけの空が広がる夜に\n「さよなら」だけだった\nその一言で全てが分かった",
        "content_ko": "가라앉듯이 녹아가듯이\n둘만의 하늘이 펼쳐지는 밤에\n「안녕」뿐이었어\n그 한마디로 전부 알았어",
        "difficulty": "N3",
        "tags": '["jpop", "yoasobi"]',
    },
    {
        "title": "アイドル",
        "artist": "YOASOBI",
        "source_type": "song",
        "content_ja": "誰もが目を奪われていく\n君は完璧で究極のアイドル\n笑顔の裏の努力を\n誰が分かってくれるだろう",
        "content_ko": "모두가 눈을 빼앗기지\n너는 완벽하고 궁극의 아이돌\n미소 뒤의 노력을\n누가 알아줄까",
        "difficulty": "N3",
        "tags": '["jpop", "yoasobi", "oshi-no-ko"]',
    },
    {
        "title": "残酷な天使のテーゼ",
        "artist": "高橋洋子",
        "source_type": "song",
        "content_ja": "残酷な天使のように\n少年よ神話になれ\n蒼い風がいま\n胸のドアを叩いても",
        "content_ko": "잔혹한 천사처럼\n소년이여 신화가 되어라\n푸른 바람이 지금\n가슴의 문을 두드려도",
        "difficulty": "N3",
        "tags": '["anime-song", "evangelion"]',
    },
    {
        "title": "紅蓮華",
        "artist": "LiSA",
        "source_type": "song",
        "content_ja": "強くなれる理由を知った\n僕を連れて進め\n泥だらけの走馬灯に酔う\nこわばる心震える手は",
        "content_ko": "강해질 수 있는 이유를 알았어\n나를 데리고 나아가\n진흙투성이 주마등에 취해\n굳어버린 마음 떨리는 손은",
        "difficulty": "N3",
        "tags": '["anime-song", "kimetsu", "lisa"]',
    },
    {
        "title": "廻廻奇譚",
        "artist": "Eve",
        "source_type": "song",
        "content_ja": "廻り廻って何回だって\n僕らは巡りあうだろう\n嘆いてばかりの夜を越えて\n朝が来るまで",
        "content_ko": "돌고 돌아 몇 번이라도\n우리는 만나게 되겠지\n한탄만 하던 밤을 넘어서\n아침이 올 때까지",
        "difficulty": "N3",
        "tags": '["anime-song", "jujutsu-kaisen"]',
    },
    {
        "title": "怪物",
        "artist": "YOASOBI",
        "source_type": "song",
        "content_ja": "僕が僕であることに\n何の意味もなかったとしても\n変わらないもの探していた\nいつだって",
        "content_ko": "내가 나인 것에\n아무 의미가 없다 해도\n변하지 않는 것을 찾고 있었어\n언제나",
        "difficulty": "N3",
        "tags": '["anime-song", "beastars", "yoasobi"]',
    },
    {
        "title": "unravel",
        "artist": "TK from 凛として時雨",
        "source_type": "song",
        "content_ja": "教えてよ 教えてよ\nその仕組みを\n僕の中に誰がいるの\n壊れた 壊れたよ この世界で",
        "content_ko": "알려줘 알려줘\n그 구조를\n내 안에 누가 있는 거야\n부서졌어 부서졌어 이 세계에서",
        "difficulty": "N3",
        "tags": '["anime-song", "tokyo-ghoul"]',
    },
    {
        "title": "シルエット",
        "artist": "KANA-BOON",
        "source_type": "song",
        "content_ja": "今が駆け出す背中押してくれる\n風の中立ち止まることなく\n走り続けるんだ\n全力疾走の毎日を",
        "content_ko": "지금이 달려나가는 등을 밀어주는\n바람 속에서 멈추지 않고\n계속 달려나가는 거야\n전력질주의 매일을",
        "difficulty": "N3",
        "tags": '["anime-song", "naruto"]',
    },
    {
        "title": "ブルーバード",
        "artist": "いきものがかり",
        "source_type": "song",
        "content_ja": "飛んでいきたいよ\n君のもとへ行きたいよ\nはばたいたら戻らないと言って\n目指したのは蒼い蒼いあの空",
        "content_ko": "날아가고 싶어\n너에게 가고 싶어\n날개를 펼치면 돌아오지 않겠다고\n목표로 한 건 파란 파란 저 하늘",
        "difficulty": "N4",
        "tags": '["anime-song", "naruto"]',
    },
    {
        "title": "群青",
        "artist": "YOASOBI",
        "source_type": "song",
        "content_ja": "嗚呼 いつもの様に\n過ぎる日々にあくびが出る\nさんざめく夜 越え今を行く\n届くかな 届くといいな",
        "content_ko": "아아 언제나처럼\n지나가는 날들에 하품이 나와\n소란스런 밤 넘어 지금을 간다\n닿을까 닿으면 좋겠다",
        "difficulty": "N3",
        "tags": '["jpop", "yoasobi"]',
    },
    {
        "title": "新時代",
        "artist": "Ado",
        "source_type": "song",
        "content_ja": "新時代はこの未来だ\n世界中全部変えてしまえばいい\n一人一人が望む世界を\nさあ始めよう",
        "content_ko": "신시대는 이 미래다\n세상 전부 바꿔버리면 돼\n한 사람 한 사람이 바라는 세계를\n자 시작하자",
        "difficulty": "N4",
        "tags": '["anime-song", "onepiece-film-red", "ado"]',
    },
    {
        "title": "逆夢",
        "artist": "King Gnu",
        "source_type": "song",
        "content_ja": "逆さまの夢を見ていた\n何もかもが狂い始めた世界で\n僕らはまだ\n信じ合えるだろうか",
        "content_ko": "거꾸로 된 꿈을 꾸고 있었어\n모든 것이 미쳐가기 시작한 세계에서\n우리는 아직\n서로 믿을 수 있을까",
        "difficulty": "N3",
        "tags": '["anime-song", "jujutsu-kaisen"]',
    },
    {
        "title": "炎",
        "artist": "LiSA",
        "source_type": "song",
        "content_ja": "さよならありがとう声の限り\n悲しみよりもっと大事なこと\n去りゆく背中に伝えたくて\n温もりと痛みに間に合うように",
        "content_ko": "안녕 고마워 목소리가 닿는 한\n슬픔보다 더 소중한 것\n떠나가는 등에 전하고 싶어서\n온기와 아픔에 닿을 수 있게",
        "difficulty": "N3",
        "tags": '["anime-song", "kimetsu", "lisa"]',
    },
    {
        "title": "ウィーアー!",
        "artist": "きただにひろし",
        "source_type": "song",
        "content_ja": "ありったけの夢をかき集め\n捜し物を探しに行くのさ\nONE PIECE\nウィーアー！",
        "content_ko": "있는 대로의 꿈을 모아\n찾는 것을 찾으러 가는 거야\nONE PIECE\n위 아!",
        "difficulty": "N4",
        "tags": '["anime-song", "onepiece"]',
    },
    {
        "title": "可愛くてごめん",
        "artist": "HoneyWorks",
        "source_type": "song",
        "content_ja": "可愛くてごめん\n盛れてる自撮りは正義\n推しに絶対届けたい\n奇跡の一枚を",
        "content_ko": "귀여워서 미안\n잘 나온 셀카는 정의\n최애에게 꼭 전하고 싶어\n기적의 한 장을",
        "difficulty": "N4",
        "tags": '["jpop", "honeyw"]',
    },
    {
        "title": "恋愛サーキュレーション",
        "artist": "花澤香菜",
        "source_type": "song",
        "content_ja": "せーの！\nでもそんなんじゃダメ\nもうそんなんじゃホラ\n心は進化するよ もっともっと",
        "content_ko": "하나둘!\n하지만 그런 건 안 돼\n이젠 그런 건 봐봐\n마음은 진화해 더더욱",
        "difficulty": "N4",
        "tags": '["anime-song", "bakemonogatari"]',
    },
    {
        "title": "オレンジ",
        "artist": "7!!",
        "source_type": "song",
        "content_ja": "雨上がりの空のような\n君の笑顔が好きだった\nいつだって側にいてくれた\nただそれだけでよかった",
        "content_ko": "비 갠 뒤 하늘 같은\n너의 웃는 얼굴이 좋았어\n언제나 곁에 있어줬잖아\n그것만으로 충분했어",
        "difficulty": "N4",
        "tags": '["anime-song", "shigatsu"]',
    },
    {
        "title": "SPECIALZ",
        "artist": "King Gnu",
        "source_type": "song",
        "content_ja": "走り出せ 走り出せ\n嘘みたいな日常を\n壊してしまえばいい\n何度だって立ち上がれ",
        "content_ko": "달려나가 달려나가\n거짓말 같은 일상을\n부숴버리면 돼\n몇 번이라도 일어나",
        "difficulty": "N4",
        "tags": '["anime-song", "jujutsu-kaisen"]',
    },
    {
        "title": "祝福",
        "artist": "YOASOBI",
        "source_type": "song",
        "content_ja": "祝福を君に\n少しでも光あれ\nまだ足りない 足りないよ\n世界を変えるその日まで",
        "content_ko": "축복을 너에게\n조금이라도 빛이 있기를\n아직 부족해 부족해\n세계를 바꾸는 그날까지",
        "difficulty": "N3",
        "tags": '["anime-song", "gundam-witch", "yoasobi"]',
    },
    {
        "title": "心臓を捧げよ!",
        "artist": "Linked Horizon",
        "source_type": "song",
        "content_ja": "捧げよ！捧げよ！\n心臓を捧げよ！\n全ての犠牲は今この瞬間のために\n進め！進め！",
        "content_ko": "바쳐라! 바쳐라!\n심장을 바쳐라!\n모든 희생은 지금 이 순간을 위해\n나아가라! 나아가라!",
        "difficulty": "N3",
        "tags": '["anime-song", "shingeki"]',
    },
    {
        "title": "フリージア",
        "artist": "Uru",
        "source_type": "song",
        "content_ja": "涙がこぼれる前に\n笑おうとしたけど\nもう無理だって分かっていた\n君がいない世界は",
        "content_ko": "눈물이 흘러내리기 전에\n웃으려 했지만\n이미 안 된다는 걸 알고 있었어\n네가 없는 세계는",
        "difficulty": "N3",
        "tags": '["anime-song", "gundam-ibo"]',
    },
    {
        "title": "God knows...",
        "artist": "涼宮ハルヒ (平野綾)",
        "source_type": "song",
        "content_ja": "渇いた心で駆け抜ける\n無機質な街の人波\n甘い言葉で塗り固めた\n嘘と本当の狭間で",
        "content_ko": "메마른 마음으로 달려나가\n무기질한 거리의 인파\n달콤한 말로 덧칠한\n거짓과 진실의 사이에서",
        "difficulty": "N2",
        "tags": '["anime-song", "haruhi"]',
    },
    {
        "title": "勇者",
        "artist": "YOASOBI",
        "source_type": "song",
        "content_ja": "世界を救う勇者は\n一人じゃないんだ\n隣にいるよずっと\n一緒に行こう",
        "content_ko": "세계를 구할 용사는\n혼자가 아니야\n옆에 있을게 계속\n같이 가자",
        "difficulty": "N4",
        "tags": '["anime-song", "frieren", "yoasobi"]',
    },
    # ═══════════════════════════════════════════════════════════
    # Anime 명대사  (35개)
    # ═══════════════════════════════════════════════════════════
    {
        "title": "진격의 거인 — 리바이 대사",
        "artist": "進撃の巨人",
        "source_type": "anime",
        "content_ja": "悔いが残らない方を自分で選べ。\nお前の判断を信じろ。\n結果がどうであれ、自分で選んだ道なら後悔はない。",
        "content_ko": "후회가 남지 않는 쪽을 스스로 선택해라.\n네 판단을 믿어라.\n결과가 어떻든, 스스로 선택한 길이라면 후회는 없다.",
        "difficulty": "N3",
        "tags": '["anime", "shingeki"]',
    },
    {
        "title": "진격의 거인 — 에렌 대사",
        "artist": "進撃の巨人",
        "source_type": "anime",
        "content_ja": "駆逐してやる！\nこの世から一匹残らず！\n戦わなければ勝てない。",
        "content_ko": "구축해버리겠어!\n이 세상에서 한 마리도 남김없이!\n싸우지 않으면 이길 수 없어.",
        "difficulty": "N4",
        "tags": '["anime", "shingeki"]',
    },
    {
        "title": "나루토 — 나루토 대사",
        "artist": "NARUTO",
        "source_type": "anime",
        "content_ja": "まっすぐ自分の言葉は曲げねえ。\nそれが俺の忍道だ！\n諦めないのが俺の忍道だってばよ！",
        "content_ko": "곧은 자신의 말은 꺾지 않아.\n그게 나의 닌자도다!\n포기하지 않는 게 나의 닌자도라고!",
        "difficulty": "N4",
        "tags": '["anime", "naruto"]',
    },
    {
        "title": "나루토 — 이타치 대사",
        "artist": "NARUTO",
        "source_type": "anime",
        "content_ja": "許せサスケ、これが最後だ。\n優しい嘘がお前を守る。\n俺はお前のことをずっと愛していた。",
        "content_ko": "용서해라 사스케, 이것이 마지막이다.\n다정한 거짓말이 너를 지킨다.\n나는 너를 계속 사랑하고 있었다.",
        "difficulty": "N3",
        "tags": '["anime", "naruto"]',
    },
    {
        "title": "나루토 — 카카시 대사",
        "artist": "NARUTO",
        "source_type": "anime",
        "content_ja": "忍びの世界でルールを破る奴はクズだ。\nだけど仲間を大切にしない奴は、\nそれ以上のクズだ。",
        "content_ko": "닌자 세계에서 규칙을 어기는 놈은 쓰레기다.\n하지만 동료를 소중히 하지 않는 놈은,\n그 이상의 쓰레기다.",
        "difficulty": "N3",
        "tags": '["anime", "naruto"]',
    },
    {
        "title": "원피스 — 루피 대사",
        "artist": "ONE PIECE",
        "source_type": "anime",
        "content_ja": "海賊王に俺はなる！\n仲間がいるよ！！\nうるせえ！！行こう！！！",
        "content_ko": "해적왕에 내가 된다!\n동료가 있잖아!!\n시끄러!! 가자!!!",
        "difficulty": "N5",
        "tags": '["anime", "onepiece"]',
    },
    {
        "title": "원피스 — 조로 대사",
        "artist": "ONE PIECE",
        "source_type": "anime",
        "content_ja": "背中の傷は剣士の恥だ。\n世界一の剣豪になるまで、\n二度と負けねえ。",
        "content_ko": "등의 상처는 검사의 수치다.\n세계 제일의 검호가 될 때까지,\n두 번 다시 지지 않겠다.",
        "difficulty": "N3",
        "tags": '["anime", "onepiece"]',
    },
    {
        "title": "원피스 — 에이스 대사",
        "artist": "ONE PIECE",
        "source_type": "anime",
        "content_ja": "愛してくれて、ありがとう。\nおれが生まれてきてよかったかなぁ。",
        "content_ko": "사랑해줘서, 고마워.\n내가 태어나길 잘한 걸까.",
        "difficulty": "N4",
        "tags": '["anime", "onepiece"]',
    },
    {
        "title": "귀멸의 칼날 — 탄지로 대사",
        "artist": "鬼滅の刃",
        "source_type": "anime",
        "content_ja": "俺は長男だから我慢できたけど、次男だったら我慢できなかった。\n頑張れ！人は心が原動力だから。",
        "content_ko": "나는 장남이니까 참을 수 있었지만, 차남이었으면 참지 못했을 거야.\n힘내! 사람은 마음이 원동력이니까.",
        "difficulty": "N3",
        "tags": '["anime", "kimetsu"]',
    },
    {
        "title": "귀멸의 칼날 — 렌고쿠 대사",
        "artist": "鬼滅の刃",
        "source_type": "anime",
        "content_ja": "心を燃やせ！\n俺は俺の責務を全うする！\n此処で誰も死なせない！",
        "content_ko": "마음을 불태워라!\n나는 나의 책무를 다한다!\n여기서 아무도 죽게 하지 않는다!",
        "difficulty": "N3",
        "tags": '["anime", "kimetsu"]',
    },
    {
        "title": "주술회전 — 고죠 대사",
        "artist": "呪術廻戦",
        "source_type": "anime",
        "content_ja": "大丈夫、僕最強だから。\n青春を謳歌しろよ。\nでないと僕を恨むことになるよ。",
        "content_ko": "괜찮아, 나 최강이니까.\n청춘을 만끽해.\n안 그러면 나를 원망하게 될 거야.",
        "difficulty": "N3",
        "tags": '["anime", "jujutsu-kaisen"]',
    },
    {
        "title": "주술회전 — 이타도리 대사",
        "artist": "呪術廻戦",
        "source_type": "anime",
        "content_ja": "正しい死を与えてやりたい。\n人を殺す呪いだからこそ、\n俺が責任を持つ。",
        "content_ko": "올바른 죽음을 줄 거야.\n사람을 죽이는 저주이기에,\n내가 책임을 진다.",
        "difficulty": "N3",
        "tags": '["anime", "jujutsu-kaisen"]',
    },
    {
        "title": "스파이 패밀리 — 로이드 대사",
        "artist": "SPY×FAMILY",
        "source_type": "anime",
        "content_ja": "子供が泣かない世界。\nそれが私の望む世界だ。\nそのために今日も任務を遂行する。",
        "content_ko": "아이가 울지 않는 세계.\n그것이 내가 바라는 세계다.\n그것을 위해 오늘도 임무를 수행한다.",
        "difficulty": "N3",
        "tags": '["anime", "spy-family"]',
    },
    {
        "title": "스파이 패밀리 — 아냐 대사",
        "artist": "SPY×FAMILY",
        "source_type": "anime",
        "content_ja": "わくわく！\nアーニャ、ピーナッツが好き！\nちちとははを応援する！",
        "content_ko": "와쿠와쿠!\n아냐, 땅콩 좋아!\n아빠랑 엄마를 응원해!",
        "difficulty": "N5",
        "tags": '["anime", "spy-family"]',
    },
    {
        "title": "체인소맨 — 덴지 대사",
        "artist": "チェンソーマン",
        "source_type": "anime",
        "content_ja": "俺の夢はな、普通の生活だ。\n朝飯食ってジャム塗ったパン食って\n女の子とイチャイチャする。それだけだ。",
        "content_ko": "내 꿈은 말이야, 보통 생활이야.\n아침밥 먹고 잼 바른 빵 먹고\n여자애랑 다정하게 지내는 것. 그것뿐이야.",
        "difficulty": "N4",
        "tags": '["anime", "chainsaw-man"]',
    },
    {
        "title": "체인소맨 — 마키마 대사",
        "artist": "チェンソーマン",
        "source_type": "anime",
        "content_ja": "私の望む世界は、より良い世界。\nそのためなら何だって利用する。\n犬には飼い主が必要でしょう？",
        "content_ko": "내가 바라는 세계는, 더 나은 세계.\n그러기 위해서라면 뭐든 이용해.\n개에게는 주인이 필요하잖아?",
        "difficulty": "N3",
        "tags": '["anime", "chainsaw-man"]',
    },
    {
        "title": "강철의 연금술사 — 에드 대사",
        "artist": "鋼の錬金術師",
        "source_type": "anime",
        "content_ja": "立って歩け、前に進め。\nあんたには立派な足がついてるじゃないか。\n等価交換だ。",
        "content_ko": "일어나 걸어, 앞으로 나아가.\n너에겐 훌륭한 다리가 있잖아.\n등가교환이다.",
        "difficulty": "N4",
        "tags": '["anime", "fullmetal"]',
    },
    {
        "title": "헌터x헌터 — 곤 대사",
        "artist": "HUNTER×HUNTER",
        "source_type": "anime",
        "content_ja": "知りたいんだ、お父さんのこと。\nどんな人だったのか。\nそのために俺はハンターになる！",
        "content_ko": "알고 싶어, 아버지에 대해.\n어떤 사람이었는지.\n그래서 나는 헌터가 될 거야!",
        "difficulty": "N4",
        "tags": '["anime", "hxh"]',
    },
    {
        "title": "헌터x헌터 — 메루엠 대사",
        "artist": "HUNTER×HUNTER",
        "source_type": "anime",
        "content_ja": "コムギ…お前といる時間が\n何よりも大切だと分かった。\n名を呼んでくれ。",
        "content_ko": "코무기…너와 함께 있는 시간이\n무엇보다 소중하다는 걸 알았다.\n이름을 불러다오.",
        "difficulty": "N3",
        "tags": '["anime", "hxh"]',
    },
    {
        "title": "에반게리온 — 신지 대사",
        "artist": "新世紀エヴァンゲリオン",
        "source_type": "anime",
        "content_ja": "逃げちゃダメだ、逃げちゃダメだ、逃げちゃダメだ。\n僕はエヴァに乗る。",
        "content_ko": "도망치면 안 돼, 도망치면 안 돼, 도망치면 안 돼.\n나는 에바에 탄다.",
        "difficulty": "N5",
        "tags": '["anime", "evangelion"]',
    },
    {
        "title": "슬램덩크 — 안자이 선생 대사",
        "artist": "SLAM DUNK",
        "source_type": "anime",
        "content_ja": "諦めたらそこで試合終了ですよ。\n君たちは強い。\n最後まで希望を捨てちゃいかん。",
        "content_ko": "포기하면 거기서 시합 종료예요.\n자네들은 강해.\n끝까지 희망을 버리면 안 돼.",
        "difficulty": "N4",
        "tags": '["anime", "slam-dunk"]',
    },
    {
        "title": "슬램덩크 — 사쿠라기 대사",
        "artist": "SLAM DUNK",
        "source_type": "anime",
        "content_ja": "天才ですから！\nこの桜木花道の実力は本物だぜ！\nリバウンドを制する者は試合を制す！",
        "content_ko": "천재니까!\n이 사쿠라기 하나미치의 실력은 진짜라고!\n리바운드를 제패하는 자가 시합을 제패한다!",
        "difficulty": "N4",
        "tags": '["anime", "slam-dunk"]',
    },
    {
        "title": "하이큐 — 히나타 대사",
        "artist": "ハイキュー!!",
        "source_type": "anime",
        "content_ja": "小さいからって負けない！\nコートの上では身長は関係ない！\n飛べるかどうかだ！",
        "content_ko": "작다고 지지 않아!\n코트 위에서는 키는 상관없어!\n날 수 있느냐의 문제야!",
        "difficulty": "N4",
        "tags": '["anime", "haikyuu"]',
    },
    {
        "title": "하이큐 — 카게야마 대사",
        "artist": "ハイキュー!!",
        "source_type": "anime",
        "content_ja": "俺がいる限り、お前は最強だ。\nトスは俺に任せろ。\n勝つぞ。",
        "content_ko": "내가 있는 한, 너는 최강이야.\n토스는 나에게 맡겨.\n이기자.",
        "difficulty": "N4",
        "tags": '["anime", "haikyuu"]',
    },
    {
        "title": "도쿄 구울 — 카네키 대사",
        "artist": "東京喰種",
        "source_type": "anime",
        "content_ja": "僕は…喰種だ。\nこの世界は間違っている。\n奪うのではなく守るために、この力を使う。",
        "content_ko": "나는…구울이다.\n이 세계는 잘못되어 있어.\n빼앗는 게 아니라 지키기 위해, 이 힘을 쓴다.",
        "difficulty": "N3",
        "tags": '["anime", "tokyo-ghoul"]',
    },
    {
        "title": "데스노트 — 라이토 대사",
        "artist": "DEATH NOTE",
        "source_type": "anime",
        "content_ja": "僕は新世界の神になる。\nこのノートで世界を変える。\n正義は僕が決める。",
        "content_ko": "나는 신세계의 신이 된다.\n이 노트로 세계를 바꾼다.\n정의는 내가 정한다.",
        "difficulty": "N4",
        "tags": '["anime", "death-note"]',
    },
    {
        "title": "데스노트 — L 대사",
        "artist": "DEATH NOTE",
        "source_type": "anime",
        "content_ja": "キラの確率は５パーセント以下…\nだが、私の正義は曲げない。\n正しいことを信じ続ける。",
        "content_ko": "키라의 확률은 5퍼센트 이하…\n하지만, 나의 정의는 꺾지 않는다.\n올바른 것을 계속 믿는다.",
        "difficulty": "N3",
        "tags": '["anime", "death-note"]',
    },
    {
        "title": "드래곤볼 — 손오공 대사",
        "artist": "ドラゴンボール",
        "source_type": "anime",
        "content_ja": "オラ、ワクワクすっぞ！\n絶対に諦めねえ！\nもっと強くなりてえ！",
        "content_ko": "나, 설레는걸!\n절대 포기 안 해!\n더 강해지고 싶어!",
        "difficulty": "N5",
        "tags": '["anime", "dragonball"]',
    },
    {
        "title": "드래곤볼 — 베지터 대사",
        "artist": "ドラゴンボール",
        "source_type": "anime",
        "content_ja": "俺はサイヤ人の王子だ！\nカカロットに負けるわけにはいかん！\nプライドが許さん！",
        "content_ko": "나는 사이어인의 왕자다!\n카카로트에게 질 수 없다!\n자존심이 허락하지 않는다!",
        "difficulty": "N4",
        "tags": '["anime", "dragonball"]',
    },
    {
        "title": "장송의 프리렌 — 프리렌 대사",
        "artist": "葬送のフリーレン",
        "source_type": "anime",
        "content_ja": "人間の寿命は短い。\nだからこそ、一緒に過ごした時間は\nもっと大切にすべきだった。",
        "content_ko": "인간의 수명은 짧다.\n그렇기에, 함께 보낸 시간은\n더 소중히 했어야 했다.",
        "difficulty": "N3",
        "tags": '["anime", "frieren"]',
    },
    {
        "title": "장송의 프리렌 — 힌멜 대사",
        "artist": "葬送のフリーレン",
        "source_type": "anime",
        "content_ja": "僕は勇者だから。\n誰かの為に何かをするのに、\n理由なんていらないだろう？",
        "content_ko": "나는 용사니까.\n누군가를 위해 무언가를 하는 데,\n이유 같은 건 필요 없잖아?",
        "difficulty": "N4",
        "tags": '["anime", "frieren"]',
    },
    {
        "title": "블리치 — 이치고 대사",
        "artist": "BLEACH",
        "source_type": "anime",
        "content_ja": "俺が守る。お前を絶対に守る。\n力がなくても、立ち上がる。\nそれが俺の戦い方だ。",
        "content_ko": "내가 지킨다. 너를 반드시 지킨다.\n힘이 없어도, 일어선다.\n그것이 나의 싸우는 방식이다.",
        "difficulty": "N4",
        "tags": '["anime", "bleach"]',
    },
    {
        "title": "은혼 — 긴토키 대사",
        "artist": "銀魂",
        "source_type": "anime",
        "content_ja": "俺の剣が届く範囲は、俺の国だ。\n美しく最期を飾る暇があるなら、\n最後まで美しく生きようじゃねぇか。",
        "content_ko": "내 칼이 닿는 범위가, 내 나라다.\n아름답게 최후를 장식할 시간이 있다면,\n끝까지 아름답게 살아보자고.",
        "difficulty": "N2",
        "tags": '["anime", "gintama"]',
    },
    {
        "title": "나의 히어로 아카데미아 — 올마이트 대사",
        "artist": "僕のヒーローアカデミア",
        "source_type": "anime",
        "content_ja": "もう大丈夫だ！\n何故って？\n私が来た！",
        "content_ko": "이제 괜찮다!\n왜냐고?\n내가 왔으니까!",
        "difficulty": "N5",
        "tags": '["anime", "mha"]',
    },
    {
        "title": "나의 히어로 아카데미아 — 데쿠 대사",
        "artist": "僕のヒーローアカデミア",
        "source_type": "anime",
        "content_ja": "無個性の僕だけど、\nヒーローになりたいんです！\n全力を出して、今ここで！",
        "content_ko": "무개성인 나지만,\n히어로가 되고 싶습니다!\n전력을 다해, 지금 여기서!",
        "difficulty": "N4",
        "tags": '["anime", "mha"]',
    },
    # ═══════════════════════════════════════════════════════════
    # Manga 명대사  (20개)
    # ═══════════════════════════════════════════════════════════
    {
        "title": "베르세르크 — 가츠 대사",
        "artist": "ベルセルク",
        "source_type": "manga",
        "content_ja": "俺は俺の剣で道を切り開く。\n運命に抗い続ける。\nそれが俺の生き方だ。",
        "content_ko": "나는 내 칼로 길을 개척한다.\n운명에 계속 저항한다.\n그것이 나의 삶의 방식이다.",
        "difficulty": "N3",
        "tags": '["manga", "berserk"]',
    },
    {
        "title": "바가본드 — 무사시 대사",
        "artist": "バガボンド",
        "source_type": "manga",
        "content_ja": "天下無双。\n強さとは何か。\nその答えを探し続ける旅だ。",
        "content_ko": "천하무쌍.\n강함이란 무엇인가.\n그 답을 찾아 계속하는 여행이다.",
        "difficulty": "N3",
        "tags": '["manga", "vagabond"]',
    },
    {
        "title": "바가본드 — 타케조 독백",
        "artist": "バガボンド",
        "source_type": "manga",
        "content_ja": "弱い自分を受け入れることから\n全ては始まる。\n本当の強さはそこにある。",
        "content_ko": "약한 자신을 받아들이는 것부터\n모든 것은 시작된다.\n진짜 강함은 거기에 있다.",
        "difficulty": "N3",
        "tags": '["manga", "vagabond"]',
    },
    {
        "title": "도쿄 리벤저스 — 타케미치 대사",
        "artist": "東京卍リベンジャーズ",
        "source_type": "manga",
        "content_ja": "俺は何度でもやり直す！\n大切な人を守るために、\n絶対に諦めない！",
        "content_ko": "나는 몇 번이든 다시 한다!\n소중한 사람을 지키기 위해,\n절대 포기하지 않아!",
        "difficulty": "N4",
        "tags": '["manga", "tokyo-revengers"]',
    },
    {
        "title": "킹덤 — 신 대사",
        "artist": "キングダム",
        "source_type": "manga",
        "content_ja": "天下の大将軍になる！\n俺は絶対に這い上がってみせる！\n約束だ！",
        "content_ko": "천하의 대장군이 된다!\n나는 반드시 기어올라가 보인다!\n약속이다!",
        "difficulty": "N4",
        "tags": '["manga", "kingdom"]',
    },
    {
        "title": "킹덤 — 왕기 대사",
        "artist": "キングダム",
        "source_type": "manga",
        "content_ja": "中華を統一する。\n戦のない世を作る。\nそれが俺の見る夢だ。",
        "content_ko": "중화를 통일한다.\n전쟁 없는 세상을 만든다.\n그것이 내가 보는 꿈이다.",
        "difficulty": "N3",
        "tags": '["manga", "kingdom"]',
    },
    {
        "title": "원펀맨 — 사이타마 대사",
        "artist": "ワンパンマン",
        "source_type": "manga",
        "content_ja": "趣味でヒーローをやっている者だ。\nワンパンで終わっちまう。\n強すぎて退屈だ。",
        "content_ko": "취미로 히어로를 하고 있는 자다.\n원펀으로 끝나버려.\n너무 강해서 지루하다.",
        "difficulty": "N4",
        "tags": '["manga", "opm"]',
    },
    {
        "title": "요츠바&! — 요츠바 대사",
        "artist": "よつばと!",
        "source_type": "manga",
        "content_ja": "今日はいい日だ！\n明日はもっといい日だ！\nとーちゃん、あそぼ！",
        "content_ko": "오늘은 좋은 날이야!\n내일은 더 좋은 날이야!\n아빠, 놀자!",
        "difficulty": "N5",
        "tags": '["manga", "yotsuba"]',
    },
    {
        "title": "시끌별 녀석들 — 라무 대사",
        "artist": "うる星やつら",
        "source_type": "manga",
        "content_ja": "ダーリン！\nうちはダーリンが好きだっちゃ！\n浮気は許さないっちゃ！",
        "content_ko": "달링!\n나는 달링이 좋다챠!\n바람은 허락 안 한다챠!",
        "difficulty": "N5",
        "tags": '["manga", "urusei"]',
    },
    {
        "title": "카이지 — 카이지 독백",
        "artist": "カイジ",
        "source_type": "manga",
        "content_ja": "勝たなきゃダメだ…！\nここで負けたら全てが終わる！\n圧倒的…！圧倒的感謝…！",
        "content_ko": "이겨야만 해…!\n여기서 지면 전부 끝난다!\n압도적…! 압도적 감사…!",
        "difficulty": "N4",
        "tags": '["manga", "kaiji"]',
    },
    {
        "title": "20세기 소년 — 켄지 대사",
        "artist": "20世紀少年",
        "source_type": "manga",
        "content_ja": "俺たちの秘密基地を覚えているか？\n子供の頃の約束を、\n大人になっても守る。",
        "content_ko": "우리의 비밀기지를 기억하나?\n어렸을 때의 약속을,\n어른이 돼서도 지킨다.",
        "difficulty": "N4",
        "tags": '["manga", "20th-century"]',
    },
    {
        "title": "데스노트 — 류크 대사",
        "artist": "DEATH NOTE",
        "source_type": "manga",
        "content_ja": "退屈だったんだよ、死神界は。\n人間は面白い。\nリンゴは美味い。",
        "content_ko": "지루했거든, 사신계는.\n인간은 재미있어.\n사과는 맛있어.",
        "difficulty": "N4",
        "tags": '["manga", "death-note"]',
    },
    {
        "title": "도라에몽 — 도라에몽 대사",
        "artist": "ドラえもん",
        "source_type": "manga",
        "content_ja": "のび太くん、しっかりしなよ！\nでも困った時は、\n僕がいるから大丈夫。",
        "content_ko": "노비타, 정신 차려!\n하지만 곤란할 때는,\n내가 있으니까 괜찮아.",
        "difficulty": "N5",
        "tags": '["manga", "doraemon"]',
    },
    {
        "title": "나나 — 나나 대사",
        "artist": "NANA",
        "source_type": "manga",
        "content_ja": "夢を追いかけることは孤独だ。\nでも、それでも歌い続ける。\n私の音楽を信じるから。",
        "content_ko": "꿈을 쫓는 것은 외롭다.\n하지만, 그래도 계속 노래한다.\n나의 음악을 믿으니까.",
        "difficulty": "N3",
        "tags": '["manga", "nana"]',
    },
    {
        "title": "블루 록 — 이사기 대사",
        "artist": "ブルーロック",
        "source_type": "manga",
        "content_ja": "世界一のストライカーになる。\n自分のエゴを貫く。\nゴールは俺が決める。",
        "content_ko": "세계 최고의 스트라이커가 된다.\n자신의 에고를 관철한다.\n골은 내가 넣는다.",
        "difficulty": "N4",
        "tags": '["manga", "blue-lock"]',
    },
    {
        "title": "몹사이코100 — 모브 대사",
        "artist": "モブサイコ100",
        "source_type": "manga",
        "content_ja": "超能力がなくても、\n自分の足で走れる。\n変わりたいなら自分で変わるんだ。",
        "content_ko": "초능력이 없어도,\n자기 발로 달릴 수 있어.\n변하고 싶다면 스스로 변하는 거야.",
        "difficulty": "N4",
        "tags": '["manga", "mob-psycho"]',
    },
    {
        "title": "약속의 네버랜드 — 엠마 대사",
        "artist": "約束のネバーランド",
        "source_type": "manga",
        "content_ja": "全員で逃げる！\n一人も置いていかない！\nそれが私の約束！",
        "content_ko": "전원 탈출한다!\n한 명도 두고 가지 않아!\n그것이 나의 약속!",
        "difficulty": "N4",
        "tags": '["manga", "neverland"]',
    },
    {
        "title": "진격의 거인 — 아르민 독백",
        "artist": "進撃の巨人",
        "source_type": "manga",
        "content_ja": "何かを変えることのできる人間がいるとすれば、\nそれは大事なものを捨てることができる人だ。\n何も捨てることができない人には、何も変えられない。",
        "content_ko": "무언가를 바꿀 수 있는 인간이 있다면,\n그건 소중한 것을 버릴 수 있는 사람이다.\n아무것도 버릴 수 없는 사람에게는, 아무것도 바꿀 수 없다.",
        "difficulty": "N2",
        "tags": '["manga", "shingeki"]',
    },
    {
        "title": "은수저 — 하치켄 대사",
        "artist": "銀の匙",
        "source_type": "manga",
        "content_ja": "命をいただくということ。\n食べることの意味を\n初めて本当に考えた。",
        "content_ko": "생명을 받는다는 것.\n먹는 것의 의미를\n처음으로 진심으로 생각했다.",
        "difficulty": "N4",
        "tags": '["manga", "silver-spoon"]',
    },
    {
        "title": "spy×family — 요르 대사",
        "artist": "SPY×FAMILY",
        "source_type": "manga",
        "content_ja": "家族を守ること。\nそれが私の一番大切な仕事です。\n殺し…いえ、何でもありません。",
        "content_ko": "가족을 지키는 것.\n그것이 나의 가장 소중한 일입니다.\n죽…아뇨, 아무것도 아닙니다.",
        "difficulty": "N4",
        "tags": '["manga", "spy-family"]',
    },
    # ═══════════════════════════════════════════════════════════
    # Games — 재미있는 명대사  (20개)
    # ═══════════════════════════════════════════════════════════
    {
        "title": "파이널 판타지7 — 클라우드",
        "artist": "Final Fantasy VII",
        "source_type": "game",
        "content_ja": "興味ないね。\nこの星の未来は俺が守る。\n約束したんだ、必ず助けに来るって。",
        "content_ko": "흥미 없어.\n이 별의 미래는 내가 지킨다.\n약속했잖아, 반드시 도와주러 온다고.",
        "difficulty": "N4",
        "tags": '["game", "ff7"]',
    },
    {
        "title": "파이널 판타지10 — 티다",
        "artist": "Final Fantasy X",
        "source_type": "game",
        "content_ja": "いなくなっちゃったけどさ、\nこの胸の中にはずっといるよ。\n泣くのは最後にする。",
        "content_ko": "사라져버렸지만 말이야,\n이 가슴속에는 계속 있어.\n우는 건 마지막으로 할게.",
        "difficulty": "N4",
        "tags": '["game", "ff10"]',
    },
    {
        "title": "페르소나5 — 주인공",
        "artist": "Persona 5",
        "source_type": "game",
        "content_ja": "お前の罪を告白しろ！\n我は汝、汝は我。\nもう一人の自分と向き合え。",
        "content_ko": "네 죄를 고백해라!\n나는 너, 너는 나.\n또 다른 자신과 마주해라.",
        "difficulty": "N3",
        "tags": '["game", "persona"]',
    },
    {
        "title": "페르소나4 — 반인 대사",
        "artist": "Persona 4",
        "source_type": "game",
        "content_ja": "真実を見極めろ。\n霧の中に隠された答えを、\n自分の目で見つけ出す。",
        "content_ko": "진실을 꿰뚫어라.\n안개 속에 감춰진 답을,\n자기 눈으로 찾아낸다.",
        "difficulty": "N3",
        "tags": '["game", "persona"]',
    },
    {
        "title": "젤다의 전설 — 명언",
        "artist": "ゼルダの伝説",
        "source_type": "game",
        "content_ja": "時の勇者よ、目覚めなさい。\n勇気のトライフォースが光り輝く時、\n闇は退く。",
        "content_ko": "시간의 용사여, 눈을 떠라.\n용기의 트라이포스가 빛나는 때,\n어둠은 물러간다.",
        "difficulty": "N3",
        "tags": '["game", "zelda"]',
    },
    {
        "title": "메탈기어 — 스네이크",
        "artist": "Metal Gear Solid",
        "source_type": "game",
        "content_ja": "俺は伝説じゃない。\nただの兵士だ。\n戦場でしか生きられない男だ。",
        "content_ko": "나는 전설이 아니야.\n그냥 군인이야.\n전장에서밖에 살 수 없는 남자야.",
        "difficulty": "N4",
        "tags": '["game", "mgs"]',
    },
    {
        "title": "킹덤하츠 — 소라",
        "artist": "Kingdom Hearts",
        "source_type": "game",
        "content_ja": "俺の友達に手を出すな！\n心の繋がりが俺の力だ！\n光は消えない！",
        "content_ko": "내 친구에게 손대지 마!\n마음의 연결이 나의 힘이야!\n빛은 사라지지 않아!",
        "difficulty": "N4",
        "tags": '["game", "kh"]',
    },
    {
        "title": "니어 오토마타 — 2B",
        "artist": "NieR:Automata",
        "source_type": "game",
        "content_ja": "感情は禁止されている。\nそれでも、この気持ちは何だろう。\n人間になりたかった。",
        "content_ko": "감정은 금지되어 있다.\n그래도, 이 기분은 뭘까.\n인간이 되고 싶었다.",
        "difficulty": "N3",
        "tags": '["game", "nier"]',
    },
    {
        "title": "니어 오토마타 — 9S",
        "artist": "NieR:Automata",
        "source_type": "game",
        "content_ja": "全ては人類のため。\n…本当にそうなのか？\n真実を知るのが怖い。",
        "content_ko": "전부 인류를 위해.\n…정말 그런 건가?\n진실을 아는 게 무섭다.",
        "difficulty": "N3",
        "tags": '["game", "nier"]',
    },
    {
        "title": "다크소울 — 화톳불 메시지",
        "artist": "Dark Souls",
        "source_type": "game",
        "content_ja": "篝火よ、消えないでくれ。\n不死の旅は終わらない。\n死んでも、何度でも立ち上がる。",
        "content_ko": "모닥불이여, 꺼지지 말아줘.\n불사의 여행은 끝나지 않는다.\n죽어도, 몇 번이고 일어선다.",
        "difficulty": "N3",
        "tags": '["game", "dark-souls"]',
    },
    {
        "title": "용과 같이 — 키류 대사",
        "artist": "龍が如く",
        "source_type": "game",
        "content_ja": "俺は桐生一馬だ。\n極道は辞めたが、\n仁義は捨てちゃいねぇ。",
        "content_ko": "나는 키류 카즈마다.\n야쿠자는 그만뒀지만,\n의리는 버리지 않았다.",
        "difficulty": "N3",
        "tags": '["game", "yakuza"]',
    },
    {
        "title": "에이스 컴뱃 — 무선 통신",
        "artist": "ACE COMBAT",
        "source_type": "game",
        "content_ja": "空は誰のものでもない。\n翼がある限り、俺は飛ぶ。\n国境なんて空にはない。",
        "content_ko": "하늘은 누구의 것도 아니다.\n날개가 있는 한, 나는 난다.\n국경 같은 건 하늘에는 없다.",
        "difficulty": "N3",
        "tags": '["game", "ace-combat"]',
    },
    {
        "title": "크로노 트리거 — 크로노",
        "artist": "クロノ・トリガー",
        "source_type": "game",
        "content_ja": "未来は変えられる。\n過去の過ちを繰り返さないために、\n今を全力で生きる。",
        "content_ko": "미래는 바꿀 수 있다.\n과거의 실수를 반복하지 않기 위해,\n지금을 전력으로 산다.",
        "difficulty": "N3",
        "tags": '["game", "chrono-trigger"]',
    },
    {
        "title": "테일즈 — 로이드 대사",
        "artist": "テイルズ オブ シンフォニア",
        "source_type": "game",
        "content_ja": "誰かを犠牲にする世界なんて\n俺は認めない！\n全員を救う方法を探す！",
        "content_ko": "누군가를 희생시키는 세계 따위\n나는 인정 안 해!\n전원을 구하는 방법을 찾는다!",
        "difficulty": "N3",
        "tags": '["game", "tales"]',
    },
    {
        "title": "대역전재판 — 나루호도 대사",
        "artist": "逆転裁判",
        "source_type": "game",
        "content_ja": "異議あり！！\nこの証拠が真実を示している！\n被告人は無罪です！",
        "content_ko": "이의 있습니다!!\n이 증거가 진실을 가리킵니다!\n피고인은 무죄입니다!",
        "difficulty": "N3",
        "tags": '["game", "ace-attorney"]',
    },
    {
        "title": "포켓몬 — 오박사 대사",
        "artist": "ポケットモンスター",
        "source_type": "game",
        "content_ja": "ここから先は君自身の冒険だ。\nポケモンと一緒に、\n広い世界を旅しなさい。",
        "content_ko": "여기서부터는 네 자신의 모험이야.\n포켓몬과 함께,\n넓은 세계를 여행하렴.",
        "difficulty": "N5",
        "tags": '["game", "pokemon"]',
    },
    {
        "title": "파이어 엠블렘 — 마르스",
        "artist": "ファイアーエムブレム",
        "source_type": "game",
        "content_ja": "仲間と共に戦う。\n一人では勝てない戦いも、\n皆の力があれば。",
        "content_ko": "동료와 함께 싸운다.\n혼자서는 이길 수 없는 싸움도,\n모두의 힘이 있다면.",
        "difficulty": "N4",
        "tags": '["game", "fire-emblem"]',
    },
    {
        "title": "데빌메이크라이 — 단테 대사",
        "artist": "Devil May Cry",
        "source_type": "game",
        "content_ja": "パーティーの時間だ！\nこの程度じゃ物足りねえな。\nもっと楽しませてくれよ。",
        "content_ko": "파티의 시간이다!\n이 정도로는 부족한데.\n더 즐겁게 해줘.",
        "difficulty": "N4",
        "tags": '["game", "dmc"]',
    },
    {
        "title": "언더테일 — 산즈 대사",
        "artist": "UNDERTALE",
        "source_type": "game",
        "content_ja": "美しい日だ、外は。\n鳥は歌い、花は咲き…\nお前のような奴は、地獄に落ちるべきだ。",
        "content_ko": "아름다운 날이야, 밖은.\n새는 노래하고, 꽃은 피고…\n너 같은 놈은, 지옥에 떨어져야 해.",
        "difficulty": "N4",
        "tags": '["game", "undertale"]',
    },
    {
        "title": "드래곤퀘스트 — 용사",
        "artist": "ドラゴンクエスト",
        "source_type": "game",
        "content_ja": "冒険の書に記された運命。\nモンスターを倒し、世界を救え。\n勇者よ、旅立ちの時だ。",
        "content_ko": "모험의 서에 기록된 운명.\n몬스터를 쓰러뜨리고, 세계를 구해라.\n용사여, 여행을 떠날 때다.",
        "difficulty": "N4",
        "tags": '["game", "dragon-quest"]',
    },
]

# ── Source ↔ Vocab Mappings (source_title → vocab words) ──

SOURCE_VOCAB_MAP = {
    "Lemon": ["夢ならば", "忘れた", "古びた", "思い出"],
    "夜に駆ける": ["沈む", "溶ける", "広がる"],
    "紅蓮華": ["強くなれる", "進め", "心"],
    "残酷な天使のテーゼ": ["残酷", "少年", "神話"],
    "진격의 거인 — 리바이 대사": ["判断", "結果"],
    "진격의 거인 — 에렌 대사": ["駆逐", "戦う"],
    "나루토 — 나루토 대사": ["諦める", "忍道"],
    "나루토 — 카카시 대사": ["仲間", "大切"],
    "원피스 — 루피 대사": ["海賊", "仲間"],
    "원피스 — 조로 대사": ["剣士", "世界一"],
    "귀멸의 칼날 — 탄지로 대사": ["我慢", "頑張れ"],
    "귀멸의 칼날 — 렌고쿠 대사": ["心", "燃やせ"],
    "주술회전 — 고죠 대사": ["最強", "青春"],
    "스파이 패밀리 — 아냐 대사": ["好き", "応援"],
    "에반게리온 — 신지 대사": ["逃げる"],
    "슬램덩크 — 안자이 선생 대사": ["諦める", "希望"],
    "하이큐 — 히나타 대사": ["負ける", "飛べる"],
    "강철의 연금술사 — 에드 대사": ["歩く", "前に進む"],
    "드래곤볼 — 손오공 대사": ["強く", "諦める"],
    "장송의 프리렌 — 프리렌 대사": ["時間", "大切"],
}


async def seed_japanese_data() -> dict:
    """Insert seed vocabulary and sources. Skips if already seeded."""
    db = await get_db()

    # Check if already seeded
    cursor = await db.execute("SELECT COUNT(*) as cnt FROM jp_vocabulary")
    row = await cursor.fetchone()
    if row and row["cnt"] > 0:
        logger.info("Japanese data already seeded (%d vocab)", row["cnt"])
        return {"status": "already_seeded", "vocab_count": row["cnt"]}

    # Insert vocabulary
    vocab_count = 0
    for word, reading, meaning, level, pos, ex_ja, ex_ko in SEED_VOCAB:
        await db.execute(
            """INSERT INTO jp_vocabulary (word, reading, meaning, jlpt_level, part_of_speech, example_ja, example_ko)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (word, reading, meaning, level, pos, ex_ja, ex_ko),
        )
        vocab_count += 1

    # Create SRS cards for all vocab
    await db.execute(
        """INSERT INTO jp_srs_cards (vocab_id, next_review)
           SELECT id, date('now') FROM jp_vocabulary
           WHERE id NOT IN (SELECT vocab_id FROM jp_srs_cards)"""
    )

    # Insert sources
    source_count = 0
    for src in SEED_SOURCES:
        await db.execute(
            """INSERT INTO jp_sources (title, artist, source_type, content_ja, content_ko, difficulty, tags)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (src["title"], src.get("artist"), src["source_type"],
             src["content_ja"], src.get("content_ko"), src["difficulty"], src["tags"]),
        )
        source_count += 1

    # Init player stats
    await db.execute(
        """INSERT OR IGNORE INTO jp_player_stats (id, total_xp, level)
           VALUES (1, 0, 1)"""
    )

    await db.commit()
    logger.info("Japanese seed data inserted: %d vocab, %d sources", vocab_count, source_count)
    return {"status": "seeded", "vocab_count": vocab_count, "source_count": source_count}
